package com.arul.finance_backend.ledger.model;

import java.time.Instant;
import java.util.UUID;

import com.arul.finance_backend.ledger.enums.TransferStatus;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * A money movement between two accounts.
 *
 * The UNIQUE constraint on idempotency_key is the hard guarantee against
 * double payment: even if the same request is retried or two identical
 * requests race, the database will reject the second insert.
 */
@Entity
@Table(name = "transfer",
       uniqueConstraints = @UniqueConstraint(
           name = "uq_transfer_idempotency_key",
           columnNames = "idempotencyKey"))
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Transfer {

    /** Assigned by the service (UUID), not auto-generated by the DB. */
    @Id
    private UUID id;

    @Column(nullable = false, updatable = false)
    private String idempotencyKey;

    @Column(nullable = false)
    private Long sourceAccountId;

    @Column(nullable = false)
    private Long destAccountId;

    @Column(nullable = false)
    private long amountMinor;

    @Column(nullable = false, length = 3)
    private String currency;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransferStatus status;

    private String failureReason;

    @Column(nullable = false)
    private Instant createdAt;
}
